language: node_js
node_js:
  - "node"

cache: npm

script: npm run lint && npm run build

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
  message: git log --format=%B --no-merges -n 1
  local_dir: dist
  on:
    branch: dev


