language: node_js
node_js:
  - "node"
cache: npm

script: npm run lint && npm run build && git log --format=%B --no-merges -n 1

deploy:
  provider: firebase
  token: "1//07kmIJPTvEdfeCgYIARAAGAcSNwF-L9Ir_jIWFPUFDEjbyOFmYp2addFHKy1_dFkgsvmOfhtpLXaRV4Pn0bFll_Ow8xdVmQEE-EQ"
  skip_cleanup: true
  message: COMMIT_MESSAGE
  local_dir: dist
  on:
    branch: master
#after_deploy: git checkout master && git merge --no-ff $TRAVIS_PULL_REQUEST_BRANCH && git push origin master


