language: node_js
node_js:
  - 16
cache: npm
before_script: npm ci
jobs:
  include:
    - stage: lint & build
      script: npm run lint && npm run build
      if: branch != master
    - stage: deploy
      script: npm run lint && npm run build && npm install firebase-tools -g && firebase deploy --only hosting --token $FIREBASE_TOKEN
      if: branch = master
