language: node_js
node_js:
  - node
cache: npm

before_script: npm ci && npm install firebase-tools -g
jobs:
  include:
    - stage: lint & build
      script: npm run lint && npm run build
    - stage: deploy
      script: npm run lint && npm run build && npm install firebase-tools -g && firebase deploy --only functions --token $FIREBASE_TOKEN
      if: branch = master
